#!/usr/bin/env node
/**
 * Generate Kysely types from Supabase database introspection
 * Run with: pnpm db:generate
 * Outputs to: src/lib/db/types.ts
 */

import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });
dotenv.config({ path: '.env' });

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.resolve(__dirname, '../src/lib/db/types.ts');

const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('❌ Missing required environment variables:');
  console.error('   SUPABASE_URL (or VITE_SUPABASE_URL)');
  console.error('   SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface ColumnInfo {
  table_name: string;
  column_name: string;
  data_type: string;
  is_nullable: string;
  column_default: string | null;
  character_maximum_length: number | null;
  numeric_precision: number | null;
  numeric_scale: number | null;
}

async function generateTypes() {
  console.log('🔄 Generating Kysely types from Supabase...');
  
  try {
    // Query information_schema for all tables and columns
    const { data: columns, error } = await supabase
      .rpc('get_table_columns', {});
    
    // If RPC doesn't exist, fall back to direct query
    let columnData: ColumnInfo[];
    
    if (error || !columns) {
      console.log('   Using direct information_schema query...');
      const { data, error: queryError } = await supabase
        .from('information_schema.columns')
        .select('table_name, column_name, data_type, is_nullable, column_default, character_maximum_length, numeric_precision, numeric_scale')
        .in('table_schema', ['public'])
        .order('table_name')
        .order('ordinal_position');
      
      if (queryError) {
        throw queryError;
      }
      columnData = data as ColumnInfo[];
    } else {
      columnData = columns as ColumnInfo[];
    }
    
    // Group by table
    const tables = new Map<string, ColumnInfo[]>();
    for (const col of columnData) {
      if (!tables.has(col.table_name)) {
        tables.set(col.table_name, []);
      }
      tables.get(col.table_name)!.push(col);
    }
    
    // Type mapping from Postgres to TypeScript
    function mapType(pgType: string, nullable: boolean): string {
      const baseType = pgType.toLowerCase();
      let tsType: string;
      
      switch (baseType) {
        case 'uuid':
          tsType = 'string';
          break;
        case 'text':
        case 'varchar':
        case 'char':
        case 'character varying':
          tsType = 'string';
          break;
        case 'integer':
        case 'bigint':
        case 'smallint':
        case 'serial':
        case 'bigserial':
          tsType = 'number';
          break;
        case 'numeric':
        case 'decimal':
        case 'real':
        case 'double precision':
          tsType = 'number';
          break;
        case 'boolean':
          tsType = 'boolean';
          break;
        case 'timestamp with time zone':
        case 'timestamp without time zone':
        case 'timestamptz':
        case 'date':
        case 'time with time zone':
        case 'time without time zone':
          tsType = 'string'; // ISO date string
          break;
        case 'json':
        case 'jsonb':
          tsType = 'Record<string, unknown>';
          break;
        case 'uuid[]':
        case 'text[]':
        case 'varchar[]':
        case 'character varying[]':
        case 'integer[]':
        case 'bigint[]':
        case 'numeric[]':
          tsType = 'string[]';
          break;
        case 'ARRAY':
          tsType = 'unknown[]';
          break;
        default:
          tsType = 'unknown';
      }
      
      return nullable ? `${tsType} | null` : tsType;
    }
    
    // Generate the types file
    let output = `// Generated by scripts/generate-kysely-types.ts
// DO NOT EDIT MANUALLY - Run 'pnpm db:generate' to regenerate
// Source: Supabase (PostgreSQL) introspection

import type { Generated } from 'kysely';

`;

    for (const [tableName, columns] of tables) {
      // Skip Supabase internal tables
      if (tableName.startsWith('_') || tableName === 'schema_migrations' || tableName === 'supabase_migrations') {
        continue;
      }
      
      // Convert table name to PascalCase for interface name
      const interfaceName = tableName
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');
      
      output += `export interface ${interfaceName} {\n`;
      
      for (const col of columns) {
        const tsType = mapType(col.data_type, col.is_nullable === 'YES');
        const camelName = col.column_name.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
        output += `  ${camelName}: ${tsType};\n`;
      }
      
      output += `}\n\n`;
    }
    
    // Generate the Database interface for Kysely
    output += `export interface Database {\n`;
    
    for (const tableName of tables.keys()) {
      if (tableName.startsWith('_') || tableName === 'schema_migrations' || tableName === 'supabase_migrations') {
        continue;
      }
      
      const interfaceName = tableName
        .split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');
      
      output += `  ${tableName}: ${interfaceName};\n`;
    }
    
    output += `}\n\n`;
    
    // Generate Generated types for Kysely
    output += `export type DB = Generated<Database>;\n`;
    
    // Write to file
    fs.writeFileSync(OUTPUT_PATH, output);
    console.log(`✅ Types generated to ${OUTPUT_PATH}`);
    console.log(`   Tables: ${tables.size - 3} (excluding internal)`);
    
  } catch (error) {
    console.error('❌ Type generation failed:', error);
    process.exit(1);
  }
}

generateTypes();